pipeline {
    agent any

    stages {
        stage('AWS STS') {
            steps {
                echo 'AWS STS'
                sh 'aws sts get-caller-identity'
            }
        }
        stage('AWS LISTAR S3') {
            steps {
                sh 'aws s3 ls'
            }
        }
        stage('GIT CLONE') {
            steps {
                sh 'rm -rf desafiojenkins/'
                sh 'git clone https://github.com/nicolasaramb/desafiojenkins'
                sh 'ls -lrt desafiojenkins/'

            }
        }
        stage('Upload to S3') {
            steps {
                sh 'aws s3 cp desafiojenkins s3://bucket-jenkins2 --recursive'

            }
        }
    }
}
